version: '3.7'

services:
  ubuntu:
    build:
      context: .
    # tty: true
    volumes:
      - ./:/root/projects/
    environment:
      TZ: Asia/Tokyo
    command: bash -c "sh /root/projects/start_optimize.sh 85"
